# build stage
FROM node:9.11.1-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV VUE_APP_BASEPATH="/"
ENV VUE_APP_FLASK_HOST="/api"
RUN npm run build

# production stage
FROM nginx:1.13.12-alpine as production-stage
COPY nginx.default.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html
#COPY docs /usr/share/nginx/html/docs
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
