# Generated by Django 2.2.5 on 2019-11-28 09:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_article_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='label_overlap',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlabel',
            name='admin_label',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
