# Generated by Django 2.2.5 on 2019-11-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20191128_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authors',
            new_name='people',
        ),
    ]
