# Generated by Django 2.2.5 on 2019-11-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191128_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='admin_article',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
