# Generated by Django 2.2.5 on 2019-12-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_article_admin_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlabel',
            name='session_id',
            field=models.CharField(max_length=50),
        ),
    ]
