# Generated by Django 2.2.5 on 2020-01-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_article_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='label_counts',
            new_name='labeled',
        ),
        migrations.RemoveField(
            model_name='article',
            name='label_overlap',
        ),
    ]
