# Generated by Django 2.2.5 on 2020-02-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200131_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='Heidi.News', max_length=200),
            preserve_default=False,
        ),
    ]
