# Contains tasks for setting up the docker daemon
- name: install certain python modules for docker
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
    - { name: docker, version: 3.5.1 }
- name: remove docker-py
  pip:
    name: docker-py
    state: absent
